function(add_racket_test NAME)
  get_filename_component(ABSOLUTE_PATH ${NAME}.cpp ABSOLUTE)
  if (EXISTS ${ABSOLUTE_PATH})
    message(STATUS "Adding `racket` test: ${NAME}.cpp")
  else()
    message(SEND_ERROR "${ABSOLUTE_PATH} does not exist")
    return()
  endif()

  add_executable(${NAME} ${NAME}.cpp)
  set_compile_options(${NAME})
  target_link_libraries(${NAME} PRIVATE racket::racket)
endfunction()

function (add_racket_benchmark NAME)
  get_filename_component(ABSOLUTE_PATH ${NAME}.cpp ABSOLUTE)
  if (EXISTS ${ABSOLUTE_PATH})
    message(STATUS "Adding `racket` benchmark: ${NAME}.cpp")
  else()
    message(SEND_ERROR "${ABSOLUTE_PATH} does not exist")
    return()
  endif()

  add_executable(${NAME} ${NAME}.cpp)
  set_compile_options(${NAME})
  target_link_libraries(${NAME} PRIVATE racket::racket)
endfunction()
